# 默认配置文件
spring:
  profiles:
    active: dev  # 默认激活开发环境配置
  
  # 应用基本信息
  application:
    name: warehouse-inventory-system
    
  # 数据源配置 - 使用H2文件数据库（数据持久化）
  datasource:
    url: jdbc:h2:file:~/warehouse_data/warehouse_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT配置
jwt:
  secret: default-jwt-secret-key-warehouse-inventory-system-2024-very-long-secure-key-for-hmac-sha256-algorithm
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天

# 服务器配置
server:
  port: 8080

# 日志配置
logging:
  level:
    com.warehouse: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.deprecation: ERROR
